### ISSUE TITLE
Overflow error: convert np.int32 to C long in Windows

### ISSUE THREAD

**Issue by fxz89** [romcon/OPTMOD#1]
# Description
The error was found in OBC test on Energizer, where the integer data `x.data` in Python are used to create the evaluator in C (OPTMOD evaluator.pyx). The size of a C long is platform dependent, it can be 64 bit on 64 bit machine, and 32 bit on 32 bit machine, but only 32 bit for all [Windows](https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma). While the x.data is the address (1e^13 digit), the overflow error occurs in `<long*>(x.data)`.

The error happens in OPTMOD\optmod\coptmod\evaluator.pyx:
```
cdef np.ndarray[long, mode='c'] x
x = np.array(arg_ids, dtype=np.int32)
evaluator.EVALUATOR_add_node(self._ptr, type, id, value, <long*>(x.data), x.size)
```
Error Message:
```
Traceback (most recent call last):
  File "C:\Users\pfzh001\Desktop\Fan\OBC\tests\test_analyzers.py", line 53, in test_with_oos
    energizer.find_energization_sequence(file=None)
  File "C:\Users\pfzh001\Desktop\Fan\OBC\epri\obc\energizer.py", line 80, in find_energization_sequence
    raise e
  File "C:\Users\pfzh001\Desktop\Fan\OBC\epri\obc\energizer.py", line 1142, in __call__
    progress=self.prog)
  File "C:\Users\pfzh001\Desktop\Fan\OBC\epri\obc\energizer.py", line 96, in find_energization_sequence
    self.compute_solution_with_optmod(subdata, file=file, abort=abort, progress=progress)
  File "C:\Users\pfzh001\Desktop\Fan\OBC\epri\obc\energizer.py", line 909, in compute_solution_with_optmod
    info = problem.solve(solver=solver, parameters={'debug': False, 'mipgap': cplex_epgap/100., 'quiet': False})
  File "C:\Users\pfzh001\AppData\Local\Programs\Python\Python37\lib\site-packages\optmod-0.0.1-py3.7-win-amd64.egg\optmod\problem.py", line 405, in solve
    std_prob = self.__get_std_problem__(fast_evaluator=fast_evaluator)
  File "C:\Users\pfzh001\AppData\Local\Programs\Python\Python37\lib\site-packages\optmod-0.0.1-py3.7-win-amd64.egg\optmod\problem.py", line 346, in __get_std_problem__
    data[0,i].__fill_evaluator__(e)
  File "C:\Users\pfzh001\AppData\Local\Programs\Python\Python37\lib\site-packages\optmod-0.0.1-py3.7-win-amd64.egg\optmod\function.py", line 44, in __fill_evaluator__
    [id(arg) for arg in self.arguments])
  File "optmod\coptmod\evaluator.pyx", line 42, in optmod.coptmod.coptmod.Evaluator.add_node
OverflowError: Python int too large to convert to C long
```

# Reproducing
* Install OPTMOD, OPTALG, Cbc/Cplex.
* Build OBC inplace, and run `nosetests -s -v`

# Potential Resolution
* Change the C long type to long long in OPTMOD.
* Use pointer type for x.data. Need to test if the pointer type can be used as the key for hash table.

**Comment by fxz89** [comment]
Reason: overflow cause by casting 64-bit memory location to 32-bit.
Solution (changes in optmod/coptmod):
- include <inttypes.h>
- "long" type changed to "uintptr_t" in C 
- "np.int32" changed to "np.uintp" in numpy
